#pragma once

#ifndef UiLibrary_h__
#define UiLibrary_h__

#include "NKWindow.h"
#include "NKSpace.h"
#include "NKGroup.h"
#include "NKPopup.h"
#include "NKCombo.h"
#include "NKButton.h"
#include "NKEdit.h"
#include "NKImage.h"
#include "NKLabel.h"
#include "NKComboItem.h"
#include "NKCheckbox.h"
#include "NKSlider.h"
#include "NKProgress.h"
#include "NKSelectable.h"
#include "NKTree.h"
#include "NKChart.h"
#include "NKTooltip.h"
#include "NKMenu.h"
#include "NKScrollbar.h"
#include "NKColorPicker.h"
#include "NKSuperStyleObject.h"

//object
CEREAL_REGISTER_TYPE(NKBase);
CEREAL_REGISTER_TYPE(NKWindow);
CEREAL_REGISTER_TYPE(NKSpace);
CEREAL_REGISTER_TYPE(NKGroup);
CEREAL_REGISTER_TYPE(NKPopup);
CEREAL_REGISTER_TYPE(NKCombo);
CEREAL_REGISTER_TYPE(NKButton);
CEREAL_REGISTER_TYPE(NKEdit);
CEREAL_REGISTER_TYPE(NKImage);
CEREAL_REGISTER_TYPE(NKLabel);
CEREAL_REGISTER_TYPE(NKComboItem);
CEREAL_REGISTER_TYPE(NKCheckbox);
CEREAL_REGISTER_TYPE(NKSlider);
CEREAL_REGISTER_TYPE(NKProgress);
CEREAL_REGISTER_TYPE(NKSelectable);
CEREAL_REGISTER_TYPE(NKTree);
CEREAL_REGISTER_TYPE(NKChart);
CEREAL_REGISTER_TYPE(NKTooltip);
CEREAL_REGISTER_TYPE(NKMenu);
CEREAL_REGISTER_TYPE(NKScrollbar);
CEREAL_REGISTER_TYPE(NKColorPicker);
CEREAL_REGISTER_TYPE(NKSuperStyleObject);

//module
CEREAL_REGISTER_TYPE(NKBaseLabel);
CEREAL_REGISTER_TYPE(NKBaseStyle);
CEREAL_REGISTER_TYPE(NKBaseWindow);
CEREAL_REGISTER_TYPE(NKHandler);
CEREAL_REGISTER_TYPE(NKObjectFinder);
CEREAL_REGISTER_TYPE(NKProperty);
CEREAL_REGISTER_TYPE(NKTransform);

//style
CEREAL_REGISTER_TYPE(NKStyleButton);
CEREAL_REGISTER_TYPE(NKStyleChart);
CEREAL_REGISTER_TYPE(NKStyleCheckbox);
CEREAL_REGISTER_TYPE(NKStyleCombo);
CEREAL_REGISTER_TYPE(NKStyleContextualButton);
CEREAL_REGISTER_TYPE(NKStyleEdit);
CEREAL_REGISTER_TYPE(NKStyleHeader);
CEREAL_REGISTER_TYPE(NKStyleMenuButton);
CEREAL_REGISTER_TYPE(NKStyleOption);
CEREAL_REGISTER_TYPE(NKStyleProgress);
CEREAL_REGISTER_TYPE(NKStyleProperty);
CEREAL_REGISTER_TYPE(NKStyleScrollbarH);
CEREAL_REGISTER_TYPE(NKStyleScrollbarV);
CEREAL_REGISTER_TYPE(NKStyleSelectedable);
CEREAL_REGISTER_TYPE(NKStyleSlider);
CEREAL_REGISTER_TYPE(NKStyleTab);
CEREAL_REGISTER_TYPE(NKStyleText);
CEREAL_REGISTER_TYPE(NKStyleWindow);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKWindow);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseWindow, NKWindow);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleHeader, NKWindow);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleWindow, NKWindow);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKSpace);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKGroup);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseWindow, NKGroup);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleHeader, NKGroup);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleWindow, NKGroup);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKPopup);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseWindow, NKPopup);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleHeader, NKPopup);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleWindow, NKPopup);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKCombo);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleCombo, NKCombo);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKButton);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKHandler, NKButton);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseLabel, NKButton);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleButton, NKButton);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKEdit);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKHandler, NKEdit);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleEdit, NKEdit);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKImage);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKLabel);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseLabel, NKLabel);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleText, NKLabel);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKComboItem);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKHandler, NKComboItem);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseLabel, NKComboItem);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKCheckbox);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseLabel, NKCheckbox);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleCheckbox, NKCheckbox);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKSlider);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleSlider, NKSlider);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKProgress);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleProgress, NKProgress);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKSelectable);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKHandler, NKSelectable);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseLabel, NKSelectable);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleSelectedable, NKSelectable);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKTree);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseLabel, NKTree);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleTab, NKTree);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKChart);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleChart, NKChart);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKTooltip);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseLabel, NKTooltip);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKObjectFinder, NKTooltip);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleWindow, NKTooltip);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleText, NKTooltip);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKMenu);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKHandler, NKMenu);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBaseLabel, NKMenu);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleMenuButton, NKMenu);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKScrollbar);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleScrollbarH, NKScrollbar);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleScrollbarV, NKScrollbar);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKColorPicker);


CEREAL_REGISTER_POLYMORPHIC_RELATION(NKBase, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleButton, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleChart, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleCheckbox, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleCombo, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleContextualButton, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleEdit, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleHeader, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleMenuButton, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleOption, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleProgress, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleProperty, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleScrollbarH, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleScrollbarV, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleSelectedable, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleSlider, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleTab, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleText, NKSuperStyleObject);
CEREAL_REGISTER_POLYMORPHIC_RELATION(NKStyleWindow, NKSuperStyleObject);

#endif //UiLibrary_h__